dictionary/urls.py
from django.conf.urls import url

from . import views

app_name = 'dictionary'
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^saveWord/$', views.saveWord),
    url(r'^savedWords/$', views.showWords),
    url(r'^deleteWord/(?P<id>\d+)/$', views.deleteWord),
  	url(r'^sayWord/$', views.sayWord),
]

my_english_abc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^register/', views.register),
    url(r'^login/', views.login),
    url(r'^home/', views.home),
    url(r'^logout/', views.logout),
    url(r'^updateUser/', views.updateUser),
    url(r'^dictionary/', include('dictionary.urls', namespace='dictionary')),
    url(r'^video/', include('video.urls', namespace='video')),
]

video/urls.py
from django.conf.urls import url

from . import views

app_name = 'video'
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'(?P<pk>\d+)/$', views.video_detail, name='detail'),
]

dictionary/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Sentence(models.Model):
    sentence_text = models.CharField(max_length=2000, default="")
    chinese_text = models.CharField(max_length=2000, default="")
    pub_date = models.DateTimeField('date published', default="")
    user = models.ForeignKey(User, default="")

    def __str__(self):
    	return self.sentence_text

    def was_published_recently(self):
    	return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

video/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
import json

# Create your models here.

class Video(models.Model):
    title = models.CharField(max_length=200, default='a title')
    video_link = models.CharField(max_length=200)

    def __str__(self):
        return self.video_link

dictionary/views.py
from django.shortcuts import render

from dictionary.models import Sentence
from django.shortcuts import HttpResponse

import datetime


def index(request):
    #return HttpResponse("Hello, world. You are at the dictionary index.")
    #template = loader.get_template('dictionary/index.html')
    #context = {}
    #return HttpResponse(template.render(context, request))
    return render(request, 'dictionary/index.html')



def saveWord(request):
    now = datetime.datetime.now()
    current_user = request.user
    resp = "The word has successfully been saved!"
    #if request.is_ajax():
    if request.method == 'POST':
        chinese_text = request.POST.get('chinese_text')
        unicode_text = chinese_text.encode('unicode-escape')
        text = request.POST.get('text')

        sentence = Sentence(sentence_text=request.POST.get('text'), chinese_text=unicode_text, pub_date=now, user=current_user)
        sentence.save()

        #sentence.text_recording.save('test.mp3', f2, save=False)
        return HttpResponse(resp)
        #return HttpResponse(resp)

def showWords(request):
    if request.user.is_authenticated():
    	resp = "These are your saved words!"
        current_user = request.user
    	sentences = Sentence.objects.filter(user=current_user)
    	for sentence in sentences:
    		# unicode_text = sentence.chinese_text.encode('unicode-escape')
    		# print(unicode_text)
            print(sentence)
    		#sentence.chinese_text = sentence.chinese_text.encode('utf8').decode('unicode-escape')
            sentence.chinese_text = sentence.chinese_text.decode('unicode-escape')
            #sentence.chinese_text = sentence.chinese_text.decode('unicode-escape')
    		#print(sentence.chinese_text)
    	return render(request, 'dictionary/saved_sentence.html', { 'sentences': sentences })
    else:
        return render(request, 'login_error.html')


def deleteWord(request, id):
    word = Sentence.objects.get(pk=id)

    # delete the word
    word.delete()

    current_user = request.user
    sentences = Sentence.objects.filter(user=current_user)
    for sentence in sentences:
		# unicode_text = sentence.chinese_text.encode('unicode-escape')
		# print(unicode_text)
        print(sentence)
		#sentence.chinese_text = sentence.chinese_text.encode('utf8').decode('unicode-escape')
        sentence.chinese_text = sentence.chinese_text.decode('unicode-escape')
        #sentence.chinese_text = sentence.chinese_text.decode('unicode-escape')
		#print(sentence.chinese_text)
    return render(request, 'dictionary/saved_sentence.html', { 'sentences': sentences })

def sayWord(request):
    resp="hello"
    #id = 19
    #return HttpResponse(resp)
    if request.method == 'POST':
        sentence_id = request.POST.get('sentence_id')
        #return HttpResponse(sentence_id)
        word = Sentence.objects.get(pk=sentence_id)
        return HttpResponse(word)
    return HttpResponse(resp)

my_english_abc/views.py
from django.shortcuts import render

from datetime import datetime
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth
from django.contrib.auth.models import User

from django.template.loader import get_template

def index(request):
    #return HttpResponse("Hello, world. You are at the homepage of the application")
    return render(request, 'index.html', {'time': datetime.now() })
    #template = get_template('index.html')
    #html = template.render()


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            auth.login(request, new_user)
            return HttpResponseRedirect("/home")
    else:
        form = UserCreationForm()
    return render(request, "registration/register.html", {'form': form})


def login(request):
    if request.method == 'POST': 
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            # Correct password, and the user is marked "active"
            auth.login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect("/home")
        else:
        	return render(request, "login/login.html")
    else:
        # Show an error page
        return render(request, "login/login.html")

def home(request):
    #print(request.user)
    fetchedUser = User.objects.get(pk=request.user.id)
    if fetchedUser is None:
        return render(request, 'home.html')
    else:
        return render(request, 'home.html', { 'fetchedUser': fetchedUser })

def logout(request):
    auth.logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect("/")
  
def updateUser(request):
    # get the user
    user = User.objects.get(pk=request.user.id)
    print(user)
    if request.method == 'POST':
        user.first_name = request.POST['firstName']
        user.last_name = request.POST['lastName']
        user.save(update_fields=['first_name', 'last_name'])
        print(user.first_name)
        fetchedUser = getUpdatedUser(request)
        return HttpResponseRedirect('/home', {'fetchedUser': fetchedUser})

def getUpdatedUser(request):
    return User.objects.get(pk=request.user.id)

video/views.py
from django.shortcuts import get_object_or_404, render
from .models import Video

# Create your views here.
def index(request):
    #return HttpResponse("Hello, world. You are at the dictionary index.")
    if request.user.is_authenticated():
        videos = Video.objects.all()
        #output = ', '.join([str(video) for video in videos])
        return render(request, 'video/index.html', {'videos': videos })
    else:
        return render(request, 'login_error.html')


def video_detail(request, pk):
    #video = Video.objects.get(pk=pk)

    video = get_object_or_404(Video, pk=pk)
    email = 'rhsu0268@gmail.com'
    return render(request, 'video/video_detail.html', {'video': video, 'email': email})

templates/dictionary/index.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block title %}Dictionary{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'dictionary/style.css' %}" >
<div class="row">
	<h1>Welcome!</h1>
	<form action="" method="get">
		<div class="form-group">
	    	<label for="text">Sentence:</label>
			<br>
	    	<textarea rows="4" cols="50" id="sentence" onfocus="this.value='';" name="sentence">Enter your sentence here.</textarea>
			<a href="#" class="button" id="translate_text">Translate</a>
			<!--<input type="submit" class="button" id="translate_text" value="Translate">-->
			<a href="#" class="button" id="save_word">Save</a>
	  	</div>
	</form>
	<div id="result">

	</div>


</div>

<script src="../static/js/jquery.js"></script>
<script src="../static/dictionary/js/dictionary.js"></script>

{% endblock %}

templates/dictionary/saved_sentence.html
{% extends "layout.html" %}
{% load staticfiles %}


{% block title %}Saved Sentences{% endblock %}



{% block content %}

<div class="row">
	<h1 id="saved_word_title">These are your saved sentences/words:</h1>
	<table>
	  <thead>
	    <tr>
	      <th width="200">Word/Sentence</th>
	      <th width="200">Chinese Translation</th>
	      <th width="200">Say It</th>
	      <th width="200">Delete</th>
	    </tr>
	  </thead>
	  <tbody>
	  	{% for sentence in sentences %}
	    <tr>
	      <td>{{ sentence.sentence_text }}</td>
	      <td>{{ sentence.chinese_text }}</td>
	      <td>
	      	
	      	<button id="{{ sentence.id }}" class="button success">Say It</button>
	      </td>
	      <td><a href="/dictionary/deleteWord/{{ sentence.id }}" id="{{ sentence.id }}" class="button alert">Delete</a></td>
	    </tr>
	    {% endfor %}
	  </tbody>
	</table>
</div>

<!--<script src="../static/dictionary/js/jquery.js"></script>-->
<!--<script src="../static/dictionary/js/saved_sentence.js"></script>-->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'dictionary/js/saved_sentence.js' %}"></script>

{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %}myEnglishABC - Home{% endblock %}

{% block content %}
    <div class="row">
        <h1>You have been logged in!</h1>

        <h3>First Name: {{ fetchedUser.first_name }}</h3>

        <h3>Last Name: {{ fetchedUser.last_name }}</h3>
    </div>
    <div class="row">
        <h1>Update your profile</h1>

        <form action="/updateUser/" method="post">
			<p>First Name: <input type="text" name="firstName"></p>
			<p>Last Name:  <input type="text" name="lastName"></p>
			{% csrf_token %}
			<input type="submit" class="button" value="Submit">
		</form>
    </div>




{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}myEnglishABC{% endblock %}

{% block content %}

    <div class="row">
    </div>

    <div class="row">
		<div class="medium-8 columns">
			<h1>我的英文ABC</h1>
			<p><img src="/static/images/img-1.jpg"></p>
		</div>
		<div class="medium-4 columns">
		<p><img src="/static/images/img-2.jpg" alt="article promo image" alt="advertisement for deep fried Twinkies"></p>
		<p><img src="/static/images/img-3.jpg" alt="article promo image"></p>
		</div>
	</div>

    <!--
    <div class="callout large primary">
		<div class="row column text-center">
			<h1>我的英文ABC</h1>
			<h2 class="subheader">學英語</h2>
		</div>
		<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
			<ul class="orbit-container">
				<button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
				<button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
				<li class="orbit-slide is-active">
					<img src="/static/images/img-1.jpg" height="200" width="1200">
				</li>
				<li class="orbit-slide">
					<img src="/static/images/img-2.jpg" height="200" width="1200">
				</li>
				<li class="orbit-slide">
					<img src="/static/images/img-3.jpg" height="200" width="1200">
				</li>
				
			</ul>
		</div>
	</div>
	-->
	<hr>
		<div class="row column">
			<h4 style="margin: 0;" class="text-center">MAKING ENGLISH LEARNING FAST, EASY, AND FUN!</h4>
		</div>
	<hr>
		<div class="row">
	<div class="large-8 columns" style="border-right: 1px solid #E3E5E8;">
		<article>
			<div class="row">
				<div class="large-6 columns">
				<p><img src="/static/images/dictionary.jpg" alt="image for article" alt="article preview image"></p>
			</div>
			<div class="large-6 columns">
				<h5><a href="/dictionary">Dictionary</a></h5>
				<!--
				<p>
					<span><i class="fi-torso"> By Thadeus &nbsp;&nbsp;</i></span>
					<span><i class="fi-calendar"> 11/23/16 &nbsp;&nbsp;</i></span>
					<span><i class="fi-comments"> 6 comments</i></span>
				</p>
				-->
				<p>Struggling with a word, phrase or sentence? Put in a vocabulary word or sentence and have a chinese translation in less than a second. 
				</p>
			</div>
		</div>
	<hr>
		<div class="row">
		<div class="large-6 columns">
			<p><img src="/static/images/list.jpg" alt="image for article" alt="article preview image"></p>
		</div>
		<div class="large-6 columns">
			<h5><a href="/savedWords">Saved Words</a></h5>
		<!--
		<p>
			<span><i class="fi-torso"></i></span>
			<span><i class="fi-calendar"> 11/23/16 &nbsp;&nbsp;</i></span>
			<span><i class="fi-comments"> 6 comments</i></span>
		</p>
		-->
		<p>Trying to keep track of all the words, phrases, or sentences that you are learning? See a list of everything you saved and play back an english audio to help you learn and remember.</p>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="large-6 columns">
			<p><img src="/static/images/follow-me.jpg" alt="image for article" alt="article preview image"></p>
		</div>
		<div class="large-6 columns">
		<h5><a href="/video">Videos</a></h5>
		<!--
		<p>
			<span><i class="fi-torso"> By Thadeus &nbsp;&nbsp;</i></span>
			<span><i class="fi-calendar"> 11/23/16 &nbsp;&nbsp;</i></span>
			<span><i class="fi-comments"> 6 comments</i></span>
		</p>
		-->
		<p>Tired of reading your English textbook. Learn by watching the great TV series, Follow Me And Learn English!</p>
		</div>
	</div>
	<!--<hr>-->
	<!--
	<div class="row">
		<div class="large-6 columns">
		<p><img src="http://placehold.it/600x370&text=Look at me!" alt="image for article" alt="article preview image"></p>
		</div>
		<div class="large-6 columns">
			<h5><a href="#">Tutor</a></h5>
			<p>
				<span><i class="fi-torso"> By Thadeus &nbsp;&nbsp;</i></span>
				<span><i class="fi-calendar"> 11/23/16 &nbsp;&nbsp;</i></span>
				<span><i class="fi-comments"> 6 comments</i></span>
			</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae impedit beatae, ipsum delectus aperiam nesciunt magni facilis ullam.</p>
		</div>
	</div>
	-->
	<hr>
	
</article>
</div>
	<div class="large-4 columns">
	<aside>
		<div class="row small-up-3">
		<!--
		<div class="column text-center">
			<i class="fi-social-facebook"></i>
			<h6>56,009</h6>
			<p><small>FOLLOWERS</small></p>
			<br>
		</div>
		<div class="column text-center">
			<i class="fi-social-twitter"></i>
			<h6>76,905</h6>
			<p><small>FOLLOWERS</small></p>
			<br>
		</div>
		<div class="column text-center">
			<i class="fi-social-instagram"></i>
			<h6>34,099</h6>
			<p><small>FOLLOWERS</small></p>
			<br>
		</div>
		<div class="column text-center">
			<i class="fi-social-tumblr"></i>
			<h6>13,765</h6>
			<p><small>FOLLOWERS</small></p>
		</div>
		<div class="column text-center">
			<i class="fi-social-pinterest"></i>
			<h6>9,283</h6>
			<p><small>FOLLOWERS</small></p>
		</div>
		<div class="column text-center">
			<i class="fi-social-youtube"></i>
			<h6>99,000</h6>
			<p><small>FOLLOWERS</small></p>
		</div>
		-->
	</div>

	<br>

	<div class="row column">
		<p class="lead">May 29, 2016</p>
		<p>
			Welcome to myEnglishABC, an initiative to help people learn English. As we all know, when we travel to a country that we have never been to before, and do not speak the country's native language, we are often thrown into a state of fear and unease. We are afraid to walk into a restarunt, we are afraid to get on a taxi, and we may be even afraid to use the restroom. 

			<br>
			<br>
			The goal of myEnglishABC is to provide tools to help people navigate and learn English in easy and effective ways. We have an electronic dictionary functionality that allows you to look up any word or sentence and get a translation in a second. We have a way for you to save the words and sentences that you want to keep and also play it back through audio output. Finally, we have compiled a set of Follow Me videos from Great Britain to help you learn English painlessly. 
			<br>
			<br>
			Above all, we hope that this application, a work in progress will meet the challenges of some of the barriers in learning English and the most important thing is to have fun learning. 
			<br>
			<br>
			Cheers!
		</p>
	</div>
	<br>
	<!--
	<div class="row column">
		<p class="lead">TRENDING POSTS</p>
		<div class="media-object">
		<div class="media-object-section">
		<img class="thumbnail" src="http://placehold.it/100">
	</div>
	<div class="media-object-section">
		<h5>All I need is a space suit and I'm ready to go.</h5>
	</div>
	</div>
	<div class="media-object">
		<div class="media-object-section">
			<img class="thumbnail" src="http://placehold.it/100">
		</div>
		<div class="media-object-section">
			<h5>Are the stars out tonight? I don't know if it's cloudy or bright.</h5>
		</div>
	</div>
	<div class="media-object">
		<div class="media-object-section">
		<img class="thumbnail" src="http://placehold.it/100">
	</div>
	<div class="media-object-section">
		<h5>And the world keeps spinning.</h5>
	</div>
	</div>
	<div class="media-object">
		<div class="media-object-section">
		<img class="thumbnail" src="http://placehold.it/100">
	</div>
	<div class="media-object-section">
		<h5>Cold hearted orb that rules the night.</h5>
	</div>
	</div>
	</div>
	-->
</aside>
</div>
</div>

{% endblock %}

templates/layout.html
<!doctype html>
{% load static from staticfiles %}
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        {% block css %}{% endblock %}
        <script src="{% static 'js/vendor/modernizr.js' %}"></script>
        <meta class="foundation-mq">
    </head>
    <body>
        <nav class="top-bar" role="navigation">
            <section class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu role="menubar">
                    <li class="menu-text">myEnglishABC</li>
                    {% if user.is_authenticated %}
                    <li><a href="/home">Home</a></li>
                    <li><a href="/dictionary">Dictionary</a></li>
                    <li><a href="/dictionary/savedWords">Saved Words</a></li>
                    <li><a href="/video">Video</a></li>
                    {% else %}
                    <li><a href="/">Info</a></li>
                    {% endif %}
                </ul>
            </section>
            <div class="top-bar-right">
                <ul class="menu">
                    {% if user.is_authenticated %}
                    <li><a href="/logout">Logout</a></li>
                    {% else %}
                    <li><a href="/register">Register</a></li>
                    <li><a href="/login">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% if messages %}
            <div class="row">
                <div class="small-6 small-centered columns">
                    {% for message in messages %}
                        <div data-alert class="callout {{ message.tags }}">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% block content %}{% endblock %}
        <footer class="row columns">
            <hr/>
            <div class="small-6 columns">
                <p>&copy; myEnglishABC</p>
            </div>
            <div class="small-6 columns">
            </div>
        </footer>
        <!--
        <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/what-input.min.js' %}"></script>
        <script src="{% static 'js/foundation.min.js' %}"></script>
        {% block javascript %}{% endblock %}
        <script>$(document).foundation();</script>
        -->
        <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
        <script>
              $(document).foundation();
            </script>
        <script type="text/javascript" src="https://intercom.zurb.com/scripts/zcom.js"></script>
    </body>
</html>

templates/login/login.html
{% extends "layout.html" %}

{% block content %}

  {% if form.errors %}
    <p class="error">Sorry, that's not a valid username or password</p>
  {% endif %}
  	<div class="row">
  		<h1>Login</h1>
  	</div>
  	<div class="row">
		<form action="" method="post">
			{% csrf_token %}
	    	<label for="username">Username:</label>
	    	<input type="text" name="username" value="" id="username">
	    	<label for="password">Password:</label>
	    	<input type="password" name="password" value="" id="password">

	    	<input type="submit" class="button" value="login" />
	    	<input type="hidden" name="next" value="{{ next|escape }}" />
	  	</form>
	</div>

{% endblock %}

templates/video/index.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block static %}
   <link rel="stylesheet" type="text/css" href="{% static 'video/css/video.css' %}"/>
{% endblock %}

{% block title %}Videos{% endblock %}

{% block content %}
    <div class="row">
	    <h1>Video Page</h1>
	    <h3>Follow Me</h3>

	    <!--
	    <object style="height: 390px; width: 640px"><param name="movie" value="http://www.youtube.com/v/4jBuqvzGG7o?version=3"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/4jBuqvzGG7o?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="390"></object>
	    <object style="height: 390px; width: 640px"><param name="movie" value="http://www.youtube.com/v/VuPkSY1SPWI?version=3"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/VuPkSY1SPWI?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="390"></object>
		-->
		<ul>
	    {% for video in videos %}
		    <ol>
		    	<li><a href="{% url 'video:detail' pk=video.pk %}" class="video_title" style="color: red">{{video.title}}</a></li>
		    </ol>
	    {% endfor %}
		</ul>

    </div>
{% endblock %}

templates/video/video_detail.html
{% extends "layout.html" %}

{% block title %}{{video.title}}{% endblock %}

{% block content %}
    <div class="row">
    	<a href="/video" class="button secondary">Back</a>
	    <h1>{{video.title}}</h1>
        <!--<h2>{{video.video_link}}</h2>-->

        <object style="height: 390px; width: 640px"><param name="movie" value={{"http://www.youtube.com/v/"|add:video.video_link|add:"version=3"}}><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src={{"http://www.youtube.com/v/"|add:video.video_link|add:"?version=3"}} type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="940" height="690"></object>

        <div>Have questions? Contact us! {{email|urlize}}</div>
    </div>


{% endblock %}